### ISSUE TITLE
Download updates to the domains list

### ISSUE THREAD

**Issue by erikvold** [flattr/flattr-extension#29]
We want to be able to download updates of the domains list.  At the moment all we can do is periodically check for an updated list, and download the list in full.  In the future we could optimize to have diff updates.

**Comment by ThomasGreiner** [comment]
@erikvold Is there something left to work on or can we close this ticket now?

**Comment by erikvold** [comment]
https://github.com/flattr/flattr-extension/commit/be62d349733a72c01ec15fda05e6bd04927d29ce
