### ISSUE TITLE
Allow exporting all of extension data

### ISSUE THREAD

**Issue by erikvold** [flattr/flattr-extension#42]
Currently we have an export function which exports the browsing events which are recorded, but there is some extension related data which should be easy to export, such as user settings.

Basically we should allow the user to export all of the extension's db data and settings data as json.

**Comment by ThomasGreiner** [comment]
@erikvold Is there something left to work on or can we close this ticket now?

**Comment by erikvold** [comment]
https://github.com/flattr/flattr-extension/commit/499b9e06fbda02572aadc3d1a72133ab49d30525
