### ISSUE TITLE
Do follow redirects of submitted URLs

### ISSUE THREAD

**Issue by da2x** [flattr/flattr-extension#50]
This URL will show an article in Instapaper when I’m logged in to the service. However, the same URL will redirect to the original source when anyone else (like Flattr) try to access it.
https://www.instapaper.com/read/1089200768

Flattr currently credit this URL to www.instpaper.com, but it should be credited to www.androidpolice.com (the original source).

Flattr should either follow all redirects when determine the proper URL to credit, OR maintain a list of services that redirect URLs (including URL shortener services).

**Comment by ThomasGreiner** [comment]
I'm seeing various fixes that have been made by the server team on that front over the last couple of weeks. Are there any other domains where you experience this issue still?

**Comment by da2x** [comment]
Instapaper was the big one for me.

**Comment by ThomasGreiner** [comment]
Ok, in that case I'm closing this issue. Thanks.
