### ISSUE TITLE
What happen to 0.7.0 releasae?

### ISSUE THREAD

**Issue by da2x** [flattr/flattr-extension#53]
A new version was supposedly released two months ago.
https://github.com/flattr/flattr-extension/commit/d94aef67e73fa85761c6b91611d392045d151a0d

All my instances on Firefox and Chromium are still on 0.6.09. Is auto-update broken? wasn’t it ever released?

**Comment by ThomasGreiner** [comment]
It hasn't been released yet as our QA team has been busy with the recent releases of Adblock Plus which required quite some attention from them.

Anyway, testing for Flattr has started two weeks ago, which include not only extension changes but also server changes, and we're about to wrap things up there and release it soon.

**Comment by ThomasGreiner** [comment]
QA has finished testing so we're going to release version 0.7 early next week.

**Comment by da2x** [comment]
Seems to have been released today. 👍
