### ISSUE TITLE
Extension collects private Github Urls

### ISSUE THREAD

**Issue by sammacbeth** [flattr/flattr-extension#65]
**Environment**

* Flattr version: `0.7.0.16`
* Browser name and version: Cliqz 1.29.0 (fork of Firefox 69.0)
* OS name and version: OSX

**Description**

When visiting a private Github page enough times to generate a flattr, the URL is sent to the flattr backend. This could expose company secrets to the Flattr service, and may not align with users' privacy expectations. It also does not make much sense to Flattr private pages.

**Steps to reproduce**

1. Inspect network traffic from the extension `about:debugging` -> Network tab.
2. Visit a private Github repo and flattr it.

**Observed behavior**

A request is made to `api.flattr.com/bulk` containing the private Github URL.

**Expected behavior**

Private URLs should not be sent to the backend.

**Comment by joltcan** [comment]
Unfortunately there is nothing in the URL that suggest if it's a private page or not, so the extension cannot now this. This is also why we cannot ever solve this issue.

A workaround is to disable automatic Flattrs on github.com (or wherever the private URL is), just click the Flattr extension and disable, and then manually Flattr on the URL you want to support.

**Comment by sammacbeth** [comment]
That is not true. You can do a credential-less fetch to the URL. For private Github repos these return `404`:

```javascript
// public repo
fetch('https://github.com/flattr/flattr-extension', { credentials: 'omit' })
  .then(r => r.status) // === 200
// private repo
fetch('https://github.com/flattr/flattr-private', { credentials: 'omit' })
  .then(r => r.status) // === 404
// private repo (for user with access)
fetch('https://github.com/flattr/flattr-private', { credentials: 'include' })
  .then(r => r.status) // === 200
```

**Comment by joltcan** [comment]
I was referring to any possibly private URL, so that would be two requests for each URL, or a corner case for github, which I'm not sure if it sounds like a good solution either. Maybe it could be an option, but we don't have any dedicated resources for the extensions at this moment.
